// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CategoryType.
const (
	CategoryTypeExpense CategoryType = "expense"
	CategoryTypeIncome  CategoryType = "income"
)

// Valid indicates whether the value is a known member of the CategoryType enum.
func (e CategoryType) Valid() bool {
	switch e {
	case CategoryTypeExpense:
		return true
	case CategoryTypeIncome:
		return true
	default:
		return false
	}
}

// Defines values for CreateCategoryRequestType.
const (
	CreateCategoryRequestTypeExpense CreateCategoryRequestType = "expense"
	CreateCategoryRequestTypeIncome  CreateCategoryRequestType = "income"
)

// Valid indicates whether the value is a known member of the CreateCategoryRequestType enum.
func (e CreateCategoryRequestType) Valid() bool {
	switch e {
	case CreateCategoryRequestTypeExpense:
		return true
	case CreateCategoryRequestTypeIncome:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCategoryRequestType.
const (
	Expense UpdateCategoryRequestType = "expense"
	Income  UpdateCategoryRequestType = "income"
)

// Valid indicates whether the value is a known member of the UpdateCategoryRequestType enum.
func (e UpdateCategoryRequestType) Valid() bool {
	switch e {
	case Expense:
		return true
	case Income:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt *time.Time    `json:"created_at,omitempty"`
	Id        *int64        `json:"id,omitempty"`
	Name      *string       `json:"name,omitempty"`
	Type      *CategoryType `json:"type,omitempty"`
	UserId    *int64        `json:"user_id,omitempty"`
}

// CategoryType defines model for Category.Type.
type CategoryType string

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Name string                    `json:"name"`
	Type CreateCategoryRequestType `json:"type"`
}

// CreateCategoryRequestType defines model for CreateCategoryRequest.Type.
type CreateCategoryRequestType string

// CreateTransactionRequest defines model for CreateTransactionRequest.
type CreateTransactionRequest struct {
	Amount     int64              `json:"amount"`
	CategoryId int64              `json:"category_id"`
	Date       openapi_types.Date `json:"date"`
	Note       *string            `json:"note,omitempty"`
}

// DailySummary defines model for DailySummary.
type DailySummary struct {
	Balance      *int64              `json:"balance,omitempty"`
	Date         *openapi_types.Date `json:"date,omitempty"`
	TotalExpense *int64              `json:"total_expense,omitempty"`
	TotalIncome  *int64              `json:"total_income,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount     *int64              `json:"amount,omitempty"`
	CategoryId *int64              `json:"category_id,omitempty"`
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Date       *openapi_types.Date `json:"date,omitempty"`
	Id         *int64              `json:"id,omitempty"`
	Note       *string             `json:"note,omitempty"`
	UserId     *int64              `json:"user_id,omitempty"`
}

// TransactionDetail defines model for TransactionDetail.
type TransactionDetail struct {
	Balance      *int64              `json:"balance,omitempty"`
	CategoryName *string             `json:"category_name,omitempty"`
	CategoryType *string             `json:"category_type,omitempty"`
	Date         *openapi_types.Date `json:"date,omitempty"`
	Note         *string             `json:"note,omitempty"`
	TotalExpense *int64              `json:"total_expense,omitempty"`
	TotalIncome  *int64              `json:"total_income,omitempty"`
}

// UpdateCategoryRequest defines model for UpdateCategoryRequest.
type UpdateCategoryRequest struct {
	Name string                    `json:"name"`
	Type UpdateCategoryRequestType `json:"type"`
}

// UpdateCategoryRequestType defines model for UpdateCategoryRequest.Type.
type UpdateCategoryRequestType string

// UpdateTransactionRequest defines model for UpdateTransactionRequest.
type UpdateTransactionRequest struct {
	Amount     int64              `json:"amount"`
	CategoryId int64              `json:"category_id"`
	Date       openapi_types.Date `json:"date"`
	Note       *string            `json:"note,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
}

// GetTransactionsBetweenDatesWithNoteParams defines parameters for GetTransactionsBetweenDatesWithNote.
type GetTransactionsBetweenDatesWithNoteParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CreateCategoryRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = UpdateCategoryRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionRequest

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = UpdateTransactionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(ctx echo.Context) error

	// (POST /auth/register)
	Register(ctx echo.Context) error

	// (GET /categories)
	GetCategories(ctx echo.Context) error

	// (POST /categories)
	CreateCategory(ctx echo.Context) error

	// (DELETE /categories/{id})
	DeleteCategory(ctx echo.Context, id int64) error

	// (PUT /categories/{id})
	UpdateCategory(ctx echo.Context, id int64) error

	// (GET /reports/date-range)
	GetTransactionsBetweenDatesWithNote(ctx echo.Context, params GetTransactionsBetweenDatesWithNoteParams) error

	// (GET /reports/details-by-date)
	GetTransactionDetailsByDate(ctx echo.Context) error

	// (GET /reports/last30days)
	GetLast30DaysDetail(ctx echo.Context) error

	// (GET /reports/last7days)
	GetLast7DaysDetail(ctx echo.Context) error

	// (GET /reports/main-summary)
	GetMainPageSummary(ctx echo.Context) error

	// (POST /transactions)
	CreateTransaction(ctx echo.Context) error

	// (DELETE /transactions/{id})
	SoftDeleteTransaction(ctx echo.Context, id int64) error

	// (PUT /transactions/{id})
	UpdateTransaction(ctx echo.Context, id int64) error
	// Soft delete a user (set is_deleted=true)
	// (PATCH /users/{id})
	SoftDeleteUser(ctx echo.Context, id int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// GetCategories converts echo context to params.
func (w *ServerInterfaceWrapper) GetCategories(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCategories(ctx)
	return err
}

// CreateCategory converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCategory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCategory(ctx)
	return err
}

// DeleteCategory converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCategory(ctx, id)
	return err
}

// UpdateCategory converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCategory(ctx, id)
	return err
}

// GetTransactionsBetweenDatesWithNote converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactionsBetweenDatesWithNote(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsBetweenDatesWithNoteParams
	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", ctx.QueryParams(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", ctx.QueryParams(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactionsBetweenDatesWithNote(ctx, params)
	return err
}

// GetTransactionDetailsByDate converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransactionDetailsByDate(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTransactionDetailsByDate(ctx)
	return err
}

// GetLast30DaysDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetLast30DaysDetail(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLast30DaysDetail(ctx)
	return err
}

// GetLast7DaysDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetLast7DaysDetail(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLast7DaysDetail(ctx)
	return err
}

// GetMainPageSummary converts echo context to params.
func (w *ServerInterfaceWrapper) GetMainPageSummary(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMainPageSummary(ctx)
	return err
}

// CreateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransaction(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTransaction(ctx)
	return err
}

// SoftDeleteTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) SoftDeleteTransaction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SoftDeleteTransaction(ctx, id)
	return err
}

// UpdateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTransaction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTransaction(ctx, id)
	return err
}

// SoftDeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) SoftDeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SoftDeleteUser(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/register", wrapper.Register)
	router.GET(baseURL+"/categories", wrapper.GetCategories)
	router.POST(baseURL+"/categories", wrapper.CreateCategory)
	router.DELETE(baseURL+"/categories/:id", wrapper.DeleteCategory)
	router.PUT(baseURL+"/categories/:id", wrapper.UpdateCategory)
	router.GET(baseURL+"/reports/date-range", wrapper.GetTransactionsBetweenDatesWithNote)
	router.GET(baseURL+"/reports/details-by-date", wrapper.GetTransactionDetailsByDate)
	router.GET(baseURL+"/reports/last30days", wrapper.GetLast30DaysDetail)
	router.GET(baseURL+"/reports/last7days", wrapper.GetLast7DaysDetail)
	router.GET(baseURL+"/reports/main-summary", wrapper.GetMainPageSummary)
	router.POST(baseURL+"/transactions", wrapper.CreateTransaction)
	router.DELETE(baseURL+"/transactions/:id", wrapper.SoftDeleteTransaction)
	router.PUT(baseURL+"/transactions/:id", wrapper.UpdateTransaction)
	router.PATCH(baseURL+"/users/:id", wrapper.SoftDeleteUser)

}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetCategoriesRequestObject struct {
}

type GetCategoriesResponseObject interface {
	VisitGetCategoriesResponse(w http.ResponseWriter) error
}

type GetCategories200JSONResponse []Category

func (response GetCategories200JSONResponse) VisitGetCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCategoryRequestObject struct {
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory201JSONResponse Category

func (response CreateCategory201JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCategoryRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteCategoryResponseObject interface {
	VisitDeleteCategoryResponse(w http.ResponseWriter) error
}

type DeleteCategory204Response struct {
}

func (response DeleteCategory204Response) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateCategoryRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateCategoryJSONRequestBody
}

type UpdateCategoryResponseObject interface {
	VisitUpdateCategoryResponse(w http.ResponseWriter) error
}

type UpdateCategory200JSONResponse Category

func (response UpdateCategory200JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionsBetweenDatesWithNoteRequestObject struct {
	Params GetTransactionsBetweenDatesWithNoteParams
}

type GetTransactionsBetweenDatesWithNoteResponseObject interface {
	VisitGetTransactionsBetweenDatesWithNoteResponse(w http.ResponseWriter) error
}

type GetTransactionsBetweenDatesWithNote200JSONResponse []TransactionDetail

func (response GetTransactionsBetweenDatesWithNote200JSONResponse) VisitGetTransactionsBetweenDatesWithNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransactionDetailsByDateRequestObject struct {
}

type GetTransactionDetailsByDateResponseObject interface {
	VisitGetTransactionDetailsByDateResponse(w http.ResponseWriter) error
}

type GetTransactionDetailsByDate200JSONResponse []TransactionDetail

func (response GetTransactionDetailsByDate200JSONResponse) VisitGetTransactionDetailsByDateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLast30DaysDetailRequestObject struct {
}

type GetLast30DaysDetailResponseObject interface {
	VisitGetLast30DaysDetailResponse(w http.ResponseWriter) error
}

type GetLast30DaysDetail200JSONResponse []TransactionDetail

func (response GetLast30DaysDetail200JSONResponse) VisitGetLast30DaysDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLast7DaysDetailRequestObject struct {
}

type GetLast7DaysDetailResponseObject interface {
	VisitGetLast7DaysDetailResponse(w http.ResponseWriter) error
}

type GetLast7DaysDetail200JSONResponse []TransactionDetail

func (response GetLast7DaysDetail200JSONResponse) VisitGetLast7DaysDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMainPageSummaryRequestObject struct {
}

type GetMainPageSummaryResponseObject interface {
	VisitGetMainPageSummaryResponse(w http.ResponseWriter) error
}

type GetMainPageSummary200JSONResponse []DailySummary

func (response GetMainPageSummary200JSONResponse) VisitGetMainPageSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateTransactionRequestObject struct {
	Body *CreateTransactionJSONRequestBody
}

type CreateTransactionResponseObject interface {
	VisitCreateTransactionResponse(w http.ResponseWriter) error
}

type CreateTransaction201JSONResponse Transaction

func (response CreateTransaction201JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SoftDeleteTransactionRequestObject struct {
	Id int64 `json:"id"`
}

type SoftDeleteTransactionResponseObject interface {
	VisitSoftDeleteTransactionResponse(w http.ResponseWriter) error
}

type SoftDeleteTransaction204Response struct {
}

func (response SoftDeleteTransaction204Response) VisitSoftDeleteTransactionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SoftDeleteTransaction404Response struct {
}

func (response SoftDeleteTransaction404Response) VisitSoftDeleteTransactionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateTransactionRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateTransactionJSONRequestBody
}

type UpdateTransactionResponseObject interface {
	VisitUpdateTransactionResponse(w http.ResponseWriter) error
}

type UpdateTransaction200JSONResponse Transaction

func (response UpdateTransaction200JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SoftDeleteUserRequestObject struct {
	Id int64 `json:"id"`
}

type SoftDeleteUserResponseObject interface {
	VisitSoftDeleteUserResponse(w http.ResponseWriter) error
}

type SoftDeleteUser204Response struct {
}

func (response SoftDeleteUser204Response) VisitSoftDeleteUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SoftDeleteUser403Response struct {
}

func (response SoftDeleteUser403Response) VisitSoftDeleteUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type SoftDeleteUser404Response struct {
}

func (response SoftDeleteUser404Response) VisitSoftDeleteUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)

	// (GET /categories)
	GetCategories(ctx context.Context, request GetCategoriesRequestObject) (GetCategoriesResponseObject, error)

	// (POST /categories)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)

	// (DELETE /categories/{id})
	DeleteCategory(ctx context.Context, request DeleteCategoryRequestObject) (DeleteCategoryResponseObject, error)

	// (PUT /categories/{id})
	UpdateCategory(ctx context.Context, request UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error)

	// (GET /reports/date-range)
	GetTransactionsBetweenDatesWithNote(ctx context.Context, request GetTransactionsBetweenDatesWithNoteRequestObject) (GetTransactionsBetweenDatesWithNoteResponseObject, error)

	// (GET /reports/details-by-date)
	GetTransactionDetailsByDate(ctx context.Context, request GetTransactionDetailsByDateRequestObject) (GetTransactionDetailsByDateResponseObject, error)

	// (GET /reports/last30days)
	GetLast30DaysDetail(ctx context.Context, request GetLast30DaysDetailRequestObject) (GetLast30DaysDetailResponseObject, error)

	// (GET /reports/last7days)
	GetLast7DaysDetail(ctx context.Context, request GetLast7DaysDetailRequestObject) (GetLast7DaysDetailResponseObject, error)

	// (GET /reports/main-summary)
	GetMainPageSummary(ctx context.Context, request GetMainPageSummaryRequestObject) (GetMainPageSummaryResponseObject, error)

	// (POST /transactions)
	CreateTransaction(ctx context.Context, request CreateTransactionRequestObject) (CreateTransactionResponseObject, error)

	// (DELETE /transactions/{id})
	SoftDeleteTransaction(ctx context.Context, request SoftDeleteTransactionRequestObject) (SoftDeleteTransactionResponseObject, error)

	// (PUT /transactions/{id})
	UpdateTransaction(ctx context.Context, request UpdateTransactionRequestObject) (UpdateTransactionResponseObject, error)
	// Soft delete a user (set is_deleted=true)
	// (PATCH /users/{id})
	SoftDeleteUser(ctx context.Context, request SoftDeleteUserRequestObject) (SoftDeleteUserResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Register operation middleware
func (sh *strictHandler) Register(ctx echo.Context) error {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx.Request().Context(), request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		return validResponse.VisitRegisterResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCategories operation middleware
func (sh *strictHandler) GetCategories(ctx echo.Context) error {
	var request GetCategoriesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategories(ctx.Request().Context(), request.(GetCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCategoriesResponseObject); ok {
		return validResponse.VisitGetCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(ctx echo.Context) error {
	var request CreateCategoryRequestObject

	var body CreateCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx.Request().Context(), request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		return validResponse.VisitCreateCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCategory operation middleware
func (sh *strictHandler) DeleteCategory(ctx echo.Context, id int64) error {
	var request DeleteCategoryRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategory(ctx.Request().Context(), request.(DeleteCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCategoryResponseObject); ok {
		return validResponse.VisitDeleteCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateCategory operation middleware
func (sh *strictHandler) UpdateCategory(ctx echo.Context, id int64) error {
	var request UpdateCategoryRequestObject

	request.Id = id

	var body UpdateCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCategory(ctx.Request().Context(), request.(UpdateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateCategoryResponseObject); ok {
		return validResponse.VisitUpdateCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactionsBetweenDatesWithNote operation middleware
func (sh *strictHandler) GetTransactionsBetweenDatesWithNote(ctx echo.Context, params GetTransactionsBetweenDatesWithNoteParams) error {
	var request GetTransactionsBetweenDatesWithNoteRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactionsBetweenDatesWithNote(ctx.Request().Context(), request.(GetTransactionsBetweenDatesWithNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactionsBetweenDatesWithNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionsBetweenDatesWithNoteResponseObject); ok {
		return validResponse.VisitGetTransactionsBetweenDatesWithNoteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTransactionDetailsByDate operation middleware
func (sh *strictHandler) GetTransactionDetailsByDate(ctx echo.Context) error {
	var request GetTransactionDetailsByDateRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactionDetailsByDate(ctx.Request().Context(), request.(GetTransactionDetailsByDateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactionDetailsByDate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTransactionDetailsByDateResponseObject); ok {
		return validResponse.VisitGetTransactionDetailsByDateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLast30DaysDetail operation middleware
func (sh *strictHandler) GetLast30DaysDetail(ctx echo.Context) error {
	var request GetLast30DaysDetailRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLast30DaysDetail(ctx.Request().Context(), request.(GetLast30DaysDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLast30DaysDetail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLast30DaysDetailResponseObject); ok {
		return validResponse.VisitGetLast30DaysDetailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLast7DaysDetail operation middleware
func (sh *strictHandler) GetLast7DaysDetail(ctx echo.Context) error {
	var request GetLast7DaysDetailRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLast7DaysDetail(ctx.Request().Context(), request.(GetLast7DaysDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLast7DaysDetail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLast7DaysDetailResponseObject); ok {
		return validResponse.VisitGetLast7DaysDetailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMainPageSummary operation middleware
func (sh *strictHandler) GetMainPageSummary(ctx echo.Context) error {
	var request GetMainPageSummaryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMainPageSummary(ctx.Request().Context(), request.(GetMainPageSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMainPageSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMainPageSummaryResponseObject); ok {
		return validResponse.VisitGetMainPageSummaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTransaction operation middleware
func (sh *strictHandler) CreateTransaction(ctx echo.Context) error {
	var request CreateTransactionRequestObject

	var body CreateTransactionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransaction(ctx.Request().Context(), request.(CreateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransaction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTransactionResponseObject); ok {
		return validResponse.VisitCreateTransactionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SoftDeleteTransaction operation middleware
func (sh *strictHandler) SoftDeleteTransaction(ctx echo.Context, id int64) error {
	var request SoftDeleteTransactionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SoftDeleteTransaction(ctx.Request().Context(), request.(SoftDeleteTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SoftDeleteTransaction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SoftDeleteTransactionResponseObject); ok {
		return validResponse.VisitSoftDeleteTransactionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTransaction operation middleware
func (sh *strictHandler) UpdateTransaction(ctx echo.Context, id int64) error {
	var request UpdateTransactionRequestObject

	request.Id = id

	var body UpdateTransactionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTransaction(ctx.Request().Context(), request.(UpdateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTransaction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTransactionResponseObject); ok {
		return validResponse.VisitUpdateTransactionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SoftDeleteUser operation middleware
func (sh *strictHandler) SoftDeleteUser(ctx echo.Context, id int64) error {
	var request SoftDeleteUserRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SoftDeleteUser(ctx.Request().Context(), request.(SoftDeleteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SoftDeleteUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SoftDeleteUserResponseObject); ok {
		return validResponse.VisitSoftDeleteUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3W7bNhR+FYHbxQYosbsELSBgF02NDt3Srkga9CIwDEY6ltlJpEIerRMMAXuHveGe",
	"ZCAp2VJE2WqcqCmwO0siz893Pp7zSV6TUKSZ4MBRkWBNVLiClJqfL3NcXYDKBFegrzMpMpDIwDxF8Qdw",
	"86PIgAREoWQ8JqVPcgVSP/hewpIE5LvJ1sOkMj+50mvK0q93i5tPEKLe/YoixEIWXY+hBIoQLSjqq6WQ",
	"qf5FIopwhCwF4ndjYVFrLeP4/HS7jnGEWAfiE05TcGZjb6wJ8DwlwTVhPBTGF/yVgUZm7rshWAz07QTB",
	"pFpDcQG3OSjsIvKQQZc+kXCbMwmR3mFMV4vmvRF+kJQrGiITvDdImoqc48AyhFXKi8GF0+Xv8MFFBS7Q",
	"BdadvJsB+HXslRcXDjPKkuIyT1PqouwNTSgP4aFTQYE0WdS1HGbc7qmIcF9enouY9VcaUsoSJx8zqtRn",
	"IaP9+FsbjR0u0C8gZgpB7o9kk2Vtt0uLvjPUjDll/Bx4jCsSPPe/NIPKhyuRxvkZ/eDcp50OZujwvus+",
	"lYe30Aa0M8CKDoeczg3CvYzZrKjb7/3x64Xlqx39qyx64iPJRvj/SLqq9Nfh6qm/oR+qq7oMK32iIMwl",
	"w+JSi0Qb9RlQCVIrUXNgzdXr2uuvHz8Q3ypWbck+3UaxQsxIqQ0zvhQmCIaJfvJWcEhE7L18/4b45E+Q",
	"yjRg8ux4ejzVUYsMOM0YCcjJ8fT4xHRzXJmIJjTH1STRg9CALCzBNNRUk+5NRAI7J4ktIyg8E5ERB6Hg",
	"CJZ4NMsSFpodk0/Ktn8rjvdJ59YMLttkQZmDuWFVuwn4p+n0wXy3XgmM7whUKFlmJxj5/bdWIUlwPdfX",
	"FjNZTe1+2Oq5/kjI3ZUNg8B7Nhp4VlJHbgSrJlAd5hgc6P0C+Gq76kAWMIRU7cto8662Pc5USlr0UkPL",
	"Kmfl2y88j1R/91vVyCzYYraLAXdqPlmzqNSWI0jAzow2fjNzv4FfRiVNAUEqElyviW5WpofVajQgZpq0",
	"8/YbOewXCfMOSqc2xGZKNrCoqn3uKH1bWIwY+sMTzK2RRu7RuwhmA9wQTEImJKqJEQGS8hh2NZeGslJn",
	"gJ8B+IwiqI8MV++EUTiu0t3mYMpa1W4pRTqsem7VVPpuuygOsjofo19230mGNs7WRGjLout5OW9X05hW",
	"RzfFUa1EB5TUBqTOipkF6Cmj0Uo3oQpPphEtdk7Gc7NqRgtV+frGMnwxJMEX32Z+KWX8SG2/ofWl+JYy",
	"/p7GUH9uGyPF1ve9L8oOG+2yX/J2vqM+qvZxvByPLH+ame5XQE0M92qgS7FEKzfacD45KeSTU9fzdwK9",
	"pcj5frH0dfJ7LL10X1JOxyLlHdWUK5BbNmYUw9UuMprPMU+HhTocT4klevYcRZ7KwxCUWuZJUlhynnS3",
	"vRbyhkURcO/fv//xQsq5qC14AlcgPfO3Xx+3jVdeE9wT0qOJBBoVdRT7NY5PNiPCoFt7p8az94MC9Jha",
	"VPZ+1vD9aKu5Wzr9FwAA///+0mqVAh0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
