// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CategoryID int64              `json:"category_id"`
	Amount     int64              `json:"amount"`
	Note       pgtype.Text        `json:"note"`
	Date       pgtype.Date        `json:"date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	Picture      pgtype.Text        `json:"picture"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
