// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, type, created_at
`

type CreateCategoryParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, category_id, amount, note, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, category_id, amount, note, date, created_at
`

type CreateTransactionParams struct {
	UserID     int64       `json:"user_id"`
	CategoryID int64       `json:"category_id"`
	Amount     int64       `json:"amount"`
	Note       pgtype.Text `json:"note"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, picture)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, picture, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	Picture      pgtype.Text `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoriesByUser = `-- name: GetCategoriesByUser :many
SELECT id, user_id, name, type, created_at FROM categories WHERE user_id = $1
`

func (q *Queries) GetCategoriesByUser(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCategoryExpense = `-- name: GetTopCategoryExpense :many
SELECT c.name, SUM(t.amount)::bigint as total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1 AND c.type = 'expense' AND t.date BETWEEN $2 AND $3
GROUP BY c.name
ORDER BY total DESC
LIMIT 5
`

type GetTopCategoryExpenseParams struct {
	UserID int64       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetTopCategoryExpenseRow struct {
	Name  string `json:"name"`
	Total int64  `json:"total"`
}

func (q *Queries) GetTopCategoryExpense(ctx context.Context, arg GetTopCategoryExpenseParams) ([]GetTopCategoryExpenseRow, error) {
	rows, err := q.db.Query(ctx, getTopCategoryExpense, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopCategoryExpenseRow{}
	for rows.Next() {
		var i GetTopCategoryExpenseRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalByTypeAndDateRange = `-- name: GetTotalByTypeAndDateRange :one
SELECT COALESCE(SUM(t.amount), 0)::bigint as total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1 AND c.type = $2 AND t.date BETWEEN $3 AND $4
`

type GetTotalByTypeAndDateRangeParams struct {
	UserID int64       `json:"user_id"`
	Type   string      `json:"type"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetTotalByTypeAndDateRange(ctx context.Context, arg GetTotalByTypeAndDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalByTypeAndDateRange,
		arg.UserID,
		arg.Type,
		arg.Date,
		arg.Date_2,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTransactionsByUserAndDateRange = `-- name: GetTransactionsByUserAndDateRange :many
SELECT id, user_id, category_id, amount, note, date, created_at FROM transactions
WHERE user_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date DESC
`

type GetTransactionsByUserAndDateRangeParams struct {
	UserID int64       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetTransactionsByUserAndDateRange(ctx context.Context, arg GetTransactionsByUserAndDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, picture, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}
