// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"context"
)

type Querier interface {
	AddTokenToBlacklist(ctx context.Context, arg AddTokenToBlacklistParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	GetCategoriesByUser(ctx context.Context, userID int64) ([]Category, error)
	GetCategoryByIdAndUser(ctx context.Context, arg GetCategoryByIdAndUserParams) (Category, error)
	GetLast30DaysDetail(ctx context.Context, userID int64) ([]GetLast30DaysDetailRow, error)
	GetLast7DaysDetail(ctx context.Context, userID int64) ([]GetLast7DaysDetailRow, error)
	GetMainPageSummaryTransactions(ctx context.Context, userID int64) ([]GetMainPageSummaryTransactionsRow, error)
	GetTransactionDetailsByDateLimit10(ctx context.Context, userID int64) ([]GetTransactionDetailsByDateLimit10Row, error)
	GetTransactionsBetweenDatesWithNote(ctx context.Context, arg GetTransactionsBetweenDatesWithNoteParams) ([]GetTransactionsBetweenDatesWithNoteRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	IsTokenBlacklisted(ctx context.Context, jti string) (bool, error)
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error
	SoftDeleteUser(ctx context.Context, id int64) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
