// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgresql

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTokenToBlacklist = `-- name: AddTokenToBlacklist :exec
INSERT INTO blacklisted_tokens (jti, expires_at)
VALUES ($1, $2)
`

type AddTokenToBlacklistParams struct {
	Jti       string    `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) AddTokenToBlacklist(ctx context.Context, arg AddTokenToBlacklistParams) error {
	_, err := q.db.Exec(ctx, addTokenToBlacklist, arg.Jti, arg.ExpiresAt)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, type, created_at
`

type CreateCategoryParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, category_id, amount, note, date, is_deleted)
VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, user_id, category_id, amount, note, date, created_at, is_deleted
`

type CreateTransactionParams struct {
	UserID     int64       `json:"user_id"`
	CategoryID int64       `json:"category_id"`
	Amount     int64       `json:"amount"`
	Note       pgtype.Text `json:"note"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, picture, is_deleted)
VALUES ($1, $2, $3, $4, false)
RETURNING id, email, password_hash, name, picture, created_at, is_deleted
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Picture      pgtype.Text `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategoriesByUser = `-- name: GetCategoriesByUser :many
SELECT id, user_id, name, type, created_at FROM categories WHERE user_id = $1
`

func (q *Queries) GetCategoriesByUser(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByIdAndUser = `-- name: GetCategoryByIdAndUser :one
SELECT id, user_id, name, type, created_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryByIdAndUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetCategoryByIdAndUser(ctx context.Context, arg GetCategoryByIdAndUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByIdAndUser, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getLast30DaysDetail = `-- name: GetLast30DaysDetail :many
SELECT
    t.date,
    t.note,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount END), 0)::BIGINT AS total_income,
        COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount END), 0)::BIGINT AS total_expense,
        COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END), 0)::BIGINT AS balance
FROM transactions t
         JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND t.is_deleted = false
  AND t.date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY t.date, t.note
ORDER BY t.date DESC
`

type GetLast30DaysDetailRow struct {
	Date         pgtype.Date `json:"date"`
	Note         pgtype.Text `json:"note"`
	TotalIncome  int64       `json:"total_income"`
	TotalExpense int64       `json:"total_expense"`
	Balance      int64       `json:"balance"`
}

func (q *Queries) GetLast30DaysDetail(ctx context.Context, userID int64) ([]GetLast30DaysDetailRow, error) {
	rows, err := q.db.Query(ctx, getLast30DaysDetail, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLast30DaysDetailRow{}
	for rows.Next() {
		var i GetLast30DaysDetailRow
		if err := rows.Scan(
			&i.Date,
			&i.Note,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLast7DaysDetail = `-- name: GetLast7DaysDetail :many
SELECT
    t.date,
    t.note,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount END), 0)::BIGINT AS total_income,
        COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount END), 0)::BIGINT AS total_expense,
        COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END), 0)::BIGINT AS balance
FROM transactions t
         JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND t.is_deleted = false
  AND t.date >= CURRENT_DATE - INTERVAL '7 days'
GROUP BY t.date, t.note
ORDER BY t.date DESC
`

type GetLast7DaysDetailRow struct {
	Date         pgtype.Date `json:"date"`
	Note         pgtype.Text `json:"note"`
	TotalIncome  int64       `json:"total_income"`
	TotalExpense int64       `json:"total_expense"`
	Balance      int64       `json:"balance"`
}

func (q *Queries) GetLast7DaysDetail(ctx context.Context, userID int64) ([]GetLast7DaysDetailRow, error) {
	rows, err := q.db.Query(ctx, getLast7DaysDetail, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLast7DaysDetailRow{}
	for rows.Next() {
		var i GetLast7DaysDetailRow
		if err := rows.Scan(
			&i.Date,
			&i.Note,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMainPageSummaryTransactions = `-- name: GetMainPageSummaryTransactions :many
SELECT
    t.date,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount END), 0)::BIGINT AS total_income,
    COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount END), 0)::BIGINT AS total_expense,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END), 0)::BIGINT AS balance
FROM transactions t
         JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1  AND t.is_deleted = false
GROUP BY t.date
ORDER BY t.date DESC
    LIMIT 10
`

type GetMainPageSummaryTransactionsRow struct {
	Date         pgtype.Date `json:"date"`
	TotalIncome  int64       `json:"total_income"`
	TotalExpense int64       `json:"total_expense"`
	Balance      int64       `json:"balance"`
}

func (q *Queries) GetMainPageSummaryTransactions(ctx context.Context, userID int64) ([]GetMainPageSummaryTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getMainPageSummaryTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMainPageSummaryTransactionsRow{}
	for rows.Next() {
		var i GetMainPageSummaryTransactionsRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionDetailsByDateLimit10 = `-- name: GetTransactionDetailsByDateLimit10 :many
SELECT
    t.date,
    c.name AS category_name,
    c.type AS category_type,
    t.note,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount END), 0)::BIGINT AS total_income,
        COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount END), 0)::BIGINT AS total_expense,
        COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END), 0)::BIGINT AS balance
FROM transactions t
         JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.is_deleted = false
GROUP BY t.date, c.name, c.type, t.note
ORDER BY t.date DESC
    LIMIT 10
`

type GetTransactionDetailsByDateLimit10Row struct {
	Date         pgtype.Date `json:"date"`
	CategoryName string      `json:"category_name"`
	CategoryType string      `json:"category_type"`
	Note         pgtype.Text `json:"note"`
	TotalIncome  int64       `json:"total_income"`
	TotalExpense int64       `json:"total_expense"`
	Balance      int64       `json:"balance"`
}

func (q *Queries) GetTransactionDetailsByDateLimit10(ctx context.Context, userID int64) ([]GetTransactionDetailsByDateLimit10Row, error) {
	rows, err := q.db.Query(ctx, getTransactionDetailsByDateLimit10, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionDetailsByDateLimit10Row{}
	for rows.Next() {
		var i GetTransactionDetailsByDateLimit10Row
		if err := rows.Scan(
			&i.Date,
			&i.CategoryName,
			&i.CategoryType,
			&i.Note,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBetweenDatesWithNote = `-- name: GetTransactionsBetweenDatesWithNote :many
SELECT
    t.date,
    t.note,
    COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE 0 END), 0)::BIGINT AS total_income,
        COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount ELSE 0 END), 0)::BIGINT AS total_expense,
        COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END), 0)::BIGINT AS balance
FROM transactions t
         JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND t.is_deleted = false
  AND t.date BETWEEN $2 AND $3
GROUP BY t.date, t.note
ORDER BY t.date DESC
`

type GetTransactionsBetweenDatesWithNoteParams struct {
	UserID int64       `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetTransactionsBetweenDatesWithNoteRow struct {
	Date         pgtype.Date `json:"date"`
	Note         pgtype.Text `json:"note"`
	TotalIncome  int64       `json:"total_income"`
	TotalExpense int64       `json:"total_expense"`
	Balance      int64       `json:"balance"`
}

func (q *Queries) GetTransactionsBetweenDatesWithNote(ctx context.Context, arg GetTransactionsBetweenDatesWithNoteParams) ([]GetTransactionsBetweenDatesWithNoteRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsBetweenDatesWithNote, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsBetweenDatesWithNoteRow{}
	for rows.Next() {
		var i GetTransactionsBetweenDatesWithNoteRow
		if err := rows.Scan(
			&i.Date,
			&i.Note,
			&i.TotalIncome,
			&i.TotalExpense,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, picture, created_at, is_deleted FROM users WHERE email = $1 AND is_deleted = false
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const isTokenBlacklisted = `-- name: IsTokenBlacklisted :one
SELECT EXISTS(SELECT 1 FROM blacklisted_tokens WHERE jti = $1) AS blacklisted
`

func (q *Queries) IsTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenBlacklisted, jti)
	var blacklisted bool
	err := row.Scan(&blacklisted)
	return blacklisted, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET is_deleted = TRUE
WHERE id = $1 AND user_id = $2
`

type SoftDeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_deleted = true
WHERE id = $1  AND is_deleted = false
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = COALESCE($3, name),
    type = COALESCE($4, type)
WHERE id = $1 AND user_id = $2
    RETURNING id, user_id, name, type, created_at
`

type UpdateCategoryParams struct {
	ID     int64       `json:"id"`
	UserID int64       `json:"user_id"`
	Name   pgtype.Text `json:"name"`
	Type   pgtype.Text `json:"type"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $3, amount = $4, note = $5, date = $6
WHERE id = $1 AND user_id = $2
    RETURNING id, user_id, category_id, amount, note, date, created_at, is_deleted
`

type UpdateTransactionParams struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	CategoryID int64       `json:"category_id"`
	Amount     int64       `json:"amount"`
	Note       pgtype.Text `json:"note"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}
