// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCategoriesByUser(ctx context.Context, userID int64) ([]Category, error)
	GetTopCategoryExpense(ctx context.Context, arg GetTopCategoryExpenseParams) ([]GetTopCategoryExpenseRow, error)
	GetTotalByTypeAndDateRange(ctx context.Context, arg GetTotalByTypeAndDateRangeParams) (int64, error)
	GetTransactionsByUserAndDateRange(ctx context.Context, arg GetTransactionsByUserAndDateRangeParams) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
